/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: be1e16a338adb6f6133f29f4aa01381f)
interface __BaseEnv_Env {
	NODE_ENV: "production";
	MONGO_URI: string;
	JWT_SECRET: string;
	FIELD_ROOM: DurableObjectNamespace<import("./src/worker").FieldRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "FieldRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "MONGO_URI" | "JWT_SECRET">> {}
}
