name: Lint, Check & Build PR Checks

on:
  push: 
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile
      - run: cp .env.example .env
      - run: pnpm run prepare
      - run: pnpm run lint
        continue-on-error: true
      - run: pnpm run check
      - run: pnpm run build
